name: Continuous Integration

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  yesterday:
    name: Test Mobile Client
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Flutter
        uses: takuyaohashi/setup-flutter@v1
        with:
          flutter-version: "latest"
          channel: "stable"
      - name: Test
        run: |
          cd yesterday
          flutter test